[loggers]
keys = root,uvicorn,uvicorn.access,sqlalchemy,app

[handlers]
keys = console_json,console_access

[formatters]
keys = json

[logger_root]
level = INFO
handlers = console_json

[logger_uvicorn]
level = INFO
handlers = console_access
qualname = uvicorn
propagate = 0

[logger_uvicorn.access]
level = INFO
handlers = console_access
qualname = uvicorn.access
propagate = 0

[logger_sqlalchemy]
level = WARNING
handlers = console_json
qualname = sqlalchemy.engine
propagate = 0

[logger_app]
level = DEBUG
handlers = console_json
qualname = app
propagate = 0

[handler_console_json]
class = logging.StreamHandler
level = INFO
formatter = json
args = (sys.stdout,)

[handler_console_access]
class = logging.StreamHandler
level = INFO
formatter = json
args = (sys.stdout,)

[formatter_json]
class = app.core.logging_formatter.JSONFormatter
